name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-lint:
    name: Lint Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Terraform Format Check
        run: terraform fmt -check -recursive ./terraform

      - name: Terraform Init
        run: terraform -chdir=terraform/$(CLOUD) init

      - name: Terraform Validate
        run: terraform -chdir=terraform/$(CLOUD) validate

  pulumi-lint:
    name: Lint Pulumi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install
        working-directory: pulumi/$(CLOUD)

      - name: Lint Pulumi
        run: npx eslint . --ext .ts
        working-directory: pulumi/$(CLOUD)

      - name: Pulumi Preview
        run: pulumi preview --non-interactive
        working-directory: pulumi/$(CLOUD)
